### ISSUE TITLE
Updates don't appear

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-consortia#162]
@osgl @carlio 
Creating an issue for the problem you're already looking into, 

Sometimes RSR updates don't appear at some Akvo Sites. 
For example: At http://connect4change.nl the latest update is from 16 of July, while updates have been posted more recently as can be seen at http://rsr.akvo.org/projects/all/?sort=latest_update_date&locations__country=&title=&organisation=272&continent=. Also if you look at the RSR projects overview within the site, you see that updates have been added recently: http://projects.connect4change.nl/en/?sort=latest_update_date

Same for http://footballforwater.nl and http://www.washalliance.nl, although WASH Alliance seems to be solved now. 

Very curious to know what the problem is exactly and if and how it can be prevented in the future.

**Comment by lauraroverts** [comment]
@carlio Can I close this issue?

**Comment by carlio** [comment]
@lauraroverts Yep, if the updates are appearing then I think the fix worked :)
